const str = `
Derrick 戴里克 德国， 民族的统治者。 
Devin， 得文， 爱尔兰 指诗人或学者。 
Dick， 狄克， 德国， 勇猛的，大胆的。 
Dominic 多明尼克， 拉丁， 属於上帝的。 
Don， 唐， 塞尔特 世界领袖。 
Donahue 唐纳修 爱尔兰 红褐色的战士。 
Donald， 唐纳德 塞尔特 世界领袖；酋长。 
Douglas 道格拉斯， 盖尔， 来自黑海的人；深灰色。 
Drew， 杜鲁， 威尔斯 聪慧与诚实的人。 
Duke， 杜克， 拉丁， 公爵；领导者。 
Duncan， 邓肯， 盖尔， 褐色的战士；晒得黑黑的战士。 
Dunn， 唐恩， 英国， 指黑色皮肤的人。 
Dwight， 德维特 条顿， 白种人或金发碧眼的人。 
Dylan， 狄伦， 威尔斯 海洋；波浪之神。 
Earl， 额尔， 英国， 有敏锐智慧的高贵领导者。 
Ed， 艾德， 英国， 一位有钱的监护人。 
Eden， 伊登， 希伯来 伊甸园，光芒与快乐。 
Edgar， 爱德格 英国， 快乐的战士。 
Edmund， 艾德蒙 英国， 有钱的保护者。 
Edison， 爱迪生 英国， 以照顾他人而丰富自己的人。 
Edward， 爱德华 英国， 一位很有钱的财产监护人。 
Edwiin， 爱德温 英国， 有钱的朋友；财产的获得者。 
Egbert， 爱格伯特， 条顿， 非常有才能的，显赫的。 
Eli， 伊莱， 希伯来 伟大，杰出。 
Elijah， 易莱哲 希伯来 耶和华就是上帝。 
Elliot， 伊里亚德， 法国，希伯来， 虔诚信仰上帝的人。 
Ellis， 艾理斯 希伯来 上帝是救世主。 
Elmer， 爱尔玛 英国， 高贵的或有名的。 
Elroy， 爱罗伊 拉丁， 王室的，国王。 
Elton， 爱尔顿 英国， 老农场的。 
Elvis， 艾维斯 条顿， 高贵的；朋友。 
Emmanuel， 爱曼纽 希伯来 上帝与我们同在。 
Enoch， 伊诺克 希腊，希伯来， 追随者；虔诚的。 
Eric， 艾利克 斯堪的那维亚， 领导者。 
Ernest， 欧尼斯特， 德国， 热心、真实或诚挚的人。 
Eugene， 尤金， 希腊、拉丁， 有高贵血统的。 
Evan， 尔文， 塞尔特 出身名门的人。 
Everley 伊夫力 英国， 指野猪打斗的场地。 
Fabian 富宾恩 罗马 种豆之人。 
Felix 费利克斯 拉丁 幸福的或幸运的。 
Ferdinand 费迪南德 条顿 旅行，爱冒险的；谋和 
Fitch 费奇 英国 金发之人。 
Fitzgerald 费兹捷勒 英国 技术高明的造箭家。 
Ford 福特 英国 河的渡口。 
Francis 弗朗西斯 拉丁 自由之人，无拘无束的人。 
Frank 法兰克 法国 自由之人。 
Franklin 法兰克林 拉丁或德国 自由之人。 
Frederic 弗雷得力克 德国 以和平领导的统治者；强大有力的，富有的。 
Gabriel 加布力尔 希伯来 上帝的男仆；上帝的力量是很力的。 
Gale 加尔 爱尔兰 唱歌；陌生人。 
Gary 盖理 条顿 带枪矛的人；猎犬。 
Gavin 盖文 爱尔兰 战争之鹰，胜利之鹰。 
Gene 吉恩 希腊，拉丁 有高贵血统的。 
Geoffrey 杰佛理 法国 神圣的和平。 
Geoff 杰夫 法国 神圣的和平。 
George 乔治 希腊 农夫。 
Gerald 杰拉尔德 条顿 勇敢的战士。 
Gilbert 吉尔伯特 条顿 闪耀的誓言；人质。 
Giles 贾艾斯 希腊 持盾之人。 
Glenn 葛兰 塞尔特 狭窄山谷的。 
Goddard 哥达 德国 稳固，不可动摇的定律。 
Godfery 高德佛里 法国 和平之神。 
Gordon 戈登 英国 三角峰的山区；英雄；强壮的人。 
Greg 格雷格 希腊 警觉之人。 
Gregary 格雷戈里 希腊 警觉之人。 
Griffith 葛里菲兹 韦尔斯 保护家园有力之人；红润的。 
Grover 格罗佛 英国 住在小树林中的人。 
Gustave 古斯塔夫 德国或瑞典 战争。 
Guy 盖 英国 引导者；明智的；木头；年老的战士。 
Hale 霍尔 英国 英雄般的荣耀。 
Haley 哈利 爱尔兰 科学的；有发明天份的。 
Hamiltion 汉米敦 法国或诺曼底 山上的小村；光秃的山丘。 
Hardy 哈帝 德国 勇敢，人格高尚之人。 
Harlan 哈伦 条顿 来自寒冷的国度。 
Harley 哈利 英国 到处是野兔的草原或小树林。 
Harold 哈罗德 英国 领导者；作战勇猛。 
Harriet 哈丽雅特 英国 战争，军人。 
Harry 哈里 中世纪英国 战争，军人。 
Harvey 哈维 法国 有苦味的；进步的或兴隆繁茂的。 
Hayden 海登 条顿 来自围以树篱的小镇。 
Heather 海拾兹 英国 开花的石南。 
Henry 享利 条顿 管理家庭的人；家族统治者。 
Herbert 赫伯特 德国 著名或辉煌的战士。 
Herman 赫尔曼 德国 军人；男子汉。 
Hilary 希拉里 拉丁 快乐的。 
Hiram 海勒 希伯来 身份地位高尚的；尊贵的。 
Hobart 霍伯特 德国 心中的光亭。 
Hogan 霍根 爱尔兰 永远年轻的。 
Horace 哈瑞斯 拉丁 老师。 
Howar 好尔德 条顿 看守者。 
Hubery 休伯特 法国 人格光明；思想灿烂的。 
Hugh 修 德国 理性；智力；灵魂。 
Hugo 雨果 拉丁 理性；智力；灵魂。 
Humphrey 汉弗莱 条顿 和平支持者。 
Hunter 汉特 英国 以打猎为荣的人。 
Hyman 海曼 希伯来 生命。 
Ian 伊恩 苏格兰 反映上帝荣耀之人。 
Ingemar 英格马 条顿 名门的后代。 
Ingram 英格兰姆 英国 指大鸟之子，智慧的象征。 
Ira 艾勒 希伯来 警觉性高的人；未阉割的马。 
Isaac 艾萨克 希伯来 笑声。 
Isidore 伊西多 希腊 女神爱色斯的礼物。 
Ivan 艾凡 俄国 上帝仁慈的赠礼。 
Ives 埃尔维斯 英国 指剑术家。 
Jack 杰克 希伯来 上帝仁慈的赠礼。 
Jacob 雅各布 希伯来 取而代之者；跟随者。 
James 詹姆士 拉丁 取而代之者。 
Jared 贾里德 希伯来 家世，血统，出身。 
Jason 杰森 希腊 治愈伤口的人；具备丰富知识的人。 
Jay 杰 法国 蓝鸟的美丽。 
Jeff 杰夫 法国 神圣的和平。 
Jeffrey 杰弗里 法国 神圣的和平。 
Jeremy 杰勒米 希伯来 上帝之崇高。 
Jerome 哲罗姆 拉丁 神圣的名字。 
Jerry 杰理 拉丁 神圣的名字。 
Jesse 杰西 希伯来 上帝的恩赐；上帝安在。 
Jim 吉姆 拉丁 取而代之者。 
Jo 乔 希伯来 上帝还会赐予。 
John 约翰 希伯来 上帝仁慈的赐恩。 
Jonas 琼纳斯 希伯来 和平鸽。 
Jonathan 强纳生 希伯来 上帝赐予。 
Joseph 约瑟夫 希伯来 上帝还会再赐予。 
Joshua 乔休尔 希伯来 上帝所援救。 
Joyce 乔伊斯 拉丁 欢喜的。 
Julian 朱利安 希腊 头发柔软的，也代表年青人。 
Julius 朱利尔斯 希腊 头发柔软的，毛茸茸的。 
Justin 贾斯丁 拉丁 诚实的。 
Keith 基思 爱尔兰 风；树林。 
Kelly 凯利 塞尔特 战士。 
Ken 肯恩 苏格兰 一位英俊的领导者。 
Kennedy 肯尼迪 爱尔兰 武士之首，指领导者。 
Kenneth 肯尼思 苏格兰 一位英俊的领导者。 
Kent 肯特 苏格兰 英俊的领袖；辽阔的国土。 
Kerr 科尔 爱尔兰 指持矛的黑人。 
Kerwin 科尔温 爱尔兰 有一只柔和的眼睛的人；朋友 
Kevin 凯文 爱尔兰 圣人；很男性化的；出身很好的。 
Kim 金姆 英国 出生皇家堡垒草地上的人。 
King 金 英国 统治者。 
Kirk 科克 盖尔 住在教堂旁边的人。 
Kyle 凯尔 韦尔斯 一狭窄的海峡；英俊潇洒的。 
Lambert 蓝伯特 德国 聪明的治产者；光明。 
Lance 蓝斯 法国 土地；等待他人的人。 
Larry 劳瑞 拉丁 月桂树。 
Lawrence 劳伦斯 拉丁 月桂树。 
Leif 列夫 挪威 大众情人。 
Len 伦恩 条顿 强壮的狮。 
Lennon 伦农 爱尔兰 戴帽子穿斗蓬很瘦的人。 
Leo 利奥 希腊 狮；勇士。 
Leonard 伦纳德 条顿 强壮如狮。 
Leopold 利奥波德 德国 有爱国心的。 
Les 勒斯 塞尔特 来自古老的堡垒。 
Lester 里斯特 英国 营地；显赫之人。 
Levi 利瓦伊 希伯来 正联合在一起。 
Lewis 刘易斯 法国 在战场上很有名气。 
Lionel 赖昂内尔 法国 像狮子般的。 
Lou 路 法国 在战场上很有名气。 
Louis 路易斯 法国 在战场上很有名气。 
Lucien 陆斯恩 拉丁 光亮，真理。 
Luther 路德 德国 杰出的战士。 
Lyle 莱尔 法国 岛上之民。 
Lyndon 林顿 条顿 住在有菩提树的地方。 
Lynn 林恩 英国 傍湖而居者。 
Magee 麦基 爱尔兰 易发怒的人。 
Malcolm 麦尔肯 苏格兰 指传道者。 
Mandel 曼德尔 德国 指有杏仁眼的人。 
Marcus 马卡斯 罗马 指有侵略性的人。 
Marico 马里奥 拉丁 好战的人；苦战 
Mark 马克 拉丁 指有侵略性的人。 
Marlon 马伦 法国 指像小鹰或猎鹰的人。 
Marsh 玛希 法国 来自草木丛生的地区。 
Marshall 马歇尔 英国 看守马的人，君王的跟随者。 
Martin 马丁 拉丁 好战的，尚武的。 
Marvin 马文 英国 朋友。 
Matt 马特 希伯来 上帝的赠礼。 
Matthew 马休 希伯来 上帝的赠礼。 
Maurice 摩里斯 拉丁 黑皮肤的；摩尔人的。 
Max 马克斯 拉丁 最伟大的。 
Maximilian 马克西米兰 拉丁 最伟大的。 
Maxwell 马克斯韦尔 英国 深具影响力又很值得尊敬之人。 
Meredith 马勒第兹 韦尔斯 大海的保护者。 
Merle 穆尔 法国 一只画眉鸟；法国人用这个名字去称呼那些爱唱歌或爱吹哨的人。 
Merlin 莫林 英国 海边的堡垒或海边的小山丘。 
Michael 麦克 希伯来 像上帝的人。 
Michell 米契尔 英国 犹如上帝的劳耀和高贵。 
Mick 密克 希伯来 像上帝的人。 
Mike 麦克 希伯来 像上帝的人。 
Miles 麦尔斯 德国，拉丁，希腊 战士；磨石；仁慈的。 
Milo 米路 拉丁 抚养镇民的人；战士。 
Monroe 门罗 塞尔特 红沼泽。 
Montague 曼特裘 拉丁 峭急之山脉的。 
Moore 穆尔 法国 黝黑英俊的外表。 
Morgan 摩尔根 韦尔斯 指住在海边的人。 
Mortimer 摩帝马 法国 傍着静寂的湖泊居住的人。 
Morton 摩顿 英国 来自旷野之村落。 
Moses 摩西 希伯来 从海中救人的人；小孩。 
Murphy 摩菲 爱尔兰 指捍卫海强的人。 
Murray 莫雷 塞尔特 水手。 
Myron 麦伦 希腊 芳香的；甜的，芳香的。 
Nat 纳特 希伯来 礼物。 
Nathan 奈登 希伯来 赠予者。 
Nathaniel 奈宝尼尔 希伯来 上帝的赠礼。 
Neil 尼尔 英国 勇敢的人；领袖；夺得锦标者，冠军。 
Nelson 尼尔森 英国 儿子。 
Newman 纽曼 英国 受欢迎的异乡人。 
Nicholas 尼克勒斯 希腊 胜利者。 
Nick 尼克 希腊 胜利者。 
Nigel 奈哲尔 拉丁 黑头发的人。 
Noah 诺亚 希伯来 镇静的，静止的，或平安的。 
Noel 诺尔 拉丁 生日；圣诞节。 
Norman 诺曼 法国 北欧人，斯堪的那维亚人。 
Norton 诺顿 英国 来自南方村落的人。 
Ogden 欧格登 英国 来自像树流域。 
Oliver 奥利佛 拉丁 平安的人。 
Omar 奥玛 阿拉伯 长子，受到先知的教诲。 
Orville 奥利尔 法国 来自黄金城。 
Osborn 奥斯本 英国 神圣的战士，受天赐福的人。 
Oscar 奥斯卡 条顿 神圣之矛。 
Osmond 奥斯蒙 英国 受到神圣的祝福，保护。 
Oswald 奥斯维得 英国 神圣而有力的。 
Otis 奥狄斯 希腊 听觉敏锐。 
Otto 奥特 德国 富有的。 
Owen 欧恩 拉丁，韦尔斯 出身高贵，年轻的战士。 
Page 裴吉 希腊 孩子。 
Parker 帕克 英国 看守公园的人。 
Paddy 培迪 爱尔兰 出身高贵的；贵族。 
Patrick 帕特里克 拉丁 出身高贵的；贵族。 
Paul 保罗 拉丁 指矮小玲珑的人。 
Philip 菲利普 希腊 战士；好战的或尚武的；爱马者。 
Porter 波特 法国 看门人或挑夫。 
Prescott 普雷斯科特 英国 牧师的小屋。 
Primo 普利莫 意大利 长子。 
Quentin 昆特 法国 第五，第五天。 
Quennel 昆尼尔 法国 独立的橡树区。 
Quincy 昆西 拉丁 第五。 
Quinn 昆 拉丁 第五。 
Quintion 昆顿 拉丁 第五个，第五个子孙。 
Rachel 雷契尔 希伯来 母羊。 
Ralap 雷尔夫 英国 狼的忠告或狼的智慧，顾问。 
Reuben 鲁宾 希腊 一个儿子！新生者。 
Rex 雷克斯 拉丁 国王。 
Richard 理查德 德国 勇猛的，大胆的。 
Robert 罗伯特 条顿 辉煌的名声。 
Robin 罗宾 条顿 辉煌的名声，知更鸟。 
Rock 洛克 英国 岩石，非常强壮之人。 
Rod 罗德 英国 公路服务者；有名气的。 
Roderick 罗得里克 英国 很有名气；很出名的领导者。 
Rodney 罗德尼 英国 公路服务者；有名气的，仆人。 
Rudolf 鲁道夫 条顿 狼。 
Rupert 鲁伯特 条顿 辉煌的名声。 
Ryan 莱安 爱尔兰 很有潜力的国王。 
Sam 山姆 希伯来 上帝之名。 
Sampson 辛普森 希伯来 高的智慧和力量，太阳的。 
Sandy 山迪 拉丁 人类的防卫者。 
Saxon 撒克逊 英国 征服他人的持剑者。 
Scott 史考特 英国 苏格兰人，爱尔兰人。 
Sean 肖恩 爱尔兰 上帝仁慈的赠礼。 
Sebastian 夕巴斯汀 希腊 受尊敬的，庄严的。 
Sid 锡德 英国 来自菲尼基Sidon城。 
Sidney 锡得尼 英国 来自菲尼基Sidon城。 
Silvester 席尔维斯特 拉丁 来自森林。 
Simon 赛门 希伯来 聆德，扁鼻子的。 Spencer 史宾杜 英国 店主；治理者，行政官。 
Stan 史丹 英国 草原，牧场。 
Stanford 史丹佛 英国 来自多岩的津泊。 
Stanley 史丹尼 英国 草原，牧场。 
Steven 史帝文 拉丁，希腊 王冠，花冠。 
Stev 史帝夫 拉丁，希腊 王冠，花冠。 
Steward 史都华德 英国 看守者或管理者。 
Tab 塔伯 条顿 卓越，睿智。 
Taylor 泰勒 英国 做裁缝的人。 
Ted 泰德 古英国 有钱的监护人。 
Ternence 泰伦斯 拉丁 温和稳重或温柔的人；高塔。 
Theobald 希尔保特 拉丁 勇敢的神。 
Theodore 西奥多 希腊 神的赠礼或上帝的赠礼。 
Thomas 托玛士 英国，拉丁 太阳之神；一对孪生子。 
Tiffany 帝福尼 法国 显示上帝的神圣形象。 
Tim 堤姆 希腊 敬神或畏神。 
Timothy 帝摩斯 希腊 敬神或畏神。 
Tobias 托拜厄斯 希腊 上帝是我信仰的神。 
Toby 托比 希腊 上帝是我信仰的神。 
Todd 托德 英国 狐狸；指聪明狡猾的人。 
Tom 汤姆 英国，拉丁 一对孪生子太阳之神。 
Tony 汤尼 拉丁 值得赞美的，很受尊重的。 
Troy 特洛伊 法国 居住于卷发人群里的人。 
Tyler 泰勒 英国 建盖屋顶的人，制砖瓦的人。 
Tyrone 泰伦 希腊 领主或统治者。 
Ulysses 尤里西斯 希腊 智勇双主，怀恨者。 
Upton 阿普顿 英国 来自镇上前端的人。 
Uriah 尤莱亚 希伯来 耶稣是光之所在。 
Valentine 范伦铁恩 拉丁 健康的人或强壮的人。 
Valentine 范伦丁 英国 有价值的，强壮的。 
Vic 维克 拉丁 胜利者，征服者。 
Victor 维克多 拉丁 胜利者，征服者。 
Vincent 文森 拉丁 征服。 
Virgil 弗吉尔 拉丁 春天，生物欣欣向荣之状。 
Vito 维托 拉丁 很活耀，气力旺盛的人。 
Vivian 维维安 拉丁 活跃的。 
Walter 瓦尔特 古德国，法国 指率领军队的人，或有权势的战士。 
Ward 华德 英国 保卫，护卫者。 
Warner 华纳 德国 抵抗侵略的人。 
Wayne 韦恩 英国 建造马车的人，四轮马车。 
Webb 韦勃 英国 编织者。 
Webster 韦伯斯特 英国 编织者。 
Wendell 温德尔 条顿 流浪者。 
Werner 弗纳尔 德国 卫国卫邦，御侵略之人。 
Wilbur 韦尔伯 英国 种很多柳树的城市，辉煌的。 
Will 威尔 法国 一位强而有力的战士或保护者。 
William 威廉 德国，法国 强而有力的战士或保卫者。 
Willie 威利 德国 强而有力的战士或保卫者。 
Winfred 威弗列德 韦尔斯 白色的波浪；爱好和平的朋友。 
Winston 温士顿 英国 来自朋友的市镇或居处，石头。 
Wright 莱特 英国 伐木工人。 
Wythe 伟兹 法国 小战士。 
Yale 耶鲁 古英国 来自边陲地带。 
York 约克 英国 养野猪的人。 
Yves 依夫 法国 法律的守护神。 
Zachary 扎克利 希伯来 为上帝所心仪的人。 
Ziv 日杰夫 斯拉夫 到处充满活力及快乐
`;

const reg = /[a-zA-Z]+/g;
const value = str.match(reg).sort();

const fs = require('fs');
fs.writeFile('en_firstname_male.json', JSON.stringify(value).replace(/"/g, "'"), 'utf8', () => {
  console.log('Done');
});
